content/plugins/script.md
updade script.md
using cloudify's script plugin with Windows PowerShell script
no longer requires to explicitly set 'command_prefix' to 'powershell'
=> CFY-5448 document powershell command_prefix auto deduction

content/cli/local.md
I read the documents of cloudify cli, and find some errors as follows:
In docs.getcloudify.org/content/cli/local.md
AS IS 
-p, --blueprint-path=BLUEPRINT_PATH - The path to the application'sblueprint file.
TO BE
-p, --blueprint-path=BLUEPRINT_PATH - The path to the application's blueprint file.
AS IS 
Executes a workflow on the locally initialized blueprint.
TO BE
Execute a workflow on the locally initialized blueprint.
AS IS 
Usage: cfy local instances --node-id=BLUEPRINT_ID
TO BE
Usage: cfy local instances [--node-id=NODE_ID]
AS IS 
Shows the outputs of the installed bluerprint
TO BE
Could I edit the local.md and fix these errors ? 
Wish you reply and Best regard!  @gilzellner  @nir0s
=> Fix some errors in the document of cloudify cli #CFY-5653

content/intro/what-is-cloudify.md
Add links for the Diamond Plugin in what-is-cloudify.md, and It would be helpful to visit the Diamond Plugin page directly.
1. Add a link to access the plugins/diamond.md in Pluggability
AS IS
the Diamond plugin
TO BE
the [Diamond plugin]({{< relref "plugins/diamond.md" >}}) 
2. Modify a link to access the diamond web in Open-Source
The URL Diamond of  is the code in GitHub, so I suggest change it to diamond.readthedocs.io
AS IS
* [Diamond](https://github.com/python-diamond/Diamond)   
TO BE
* [Diamond](http://diamond.readthedocs.io/)
Best reguards!
=> Add links for the Diamond Plugin in docments #CFY-5689

content/installation/from-script.md
[WARNING] [get-cloudify.py] --installvirtualenv is deprecated. Use --install-virtualenv. --installvirtualenv will be removed in a future release.
=> --installvirtualenv changed to --install-virtualenv per warning

content/installation/from-packages.md
The title contains a mistaken word in from-packages.md.
AS IS 
Installing using packages for commmon OS distributions
TO BE
Installing using packages for common OS distributions
Please check it and Thanks!
=> Fix a mistaken word for title in from-packages.md

content/cli/status.md
Fix the description for the cfy status command in cli/status.md.
AS IS
To use the command you must 'cfy use -t MANAGEMENT_IP' first.
TO BE
To use the command you should `cfy use -t MANAGEMENT_IP` or `cfy bootstrap` first.  See [cfy bootstrap]({{< relref "cli/bootstrap.md" >}}) for more information.
Please check it and thanks!
=> Fix the description for the cfy status command

content/cli/recover.md
Add a required flag for the cfy recover command  in cli/recover.md. According to the required flags, we can get the massage that  " -f, --force - Force recovery. This flag is mandatory" in the required flags.
AS IS 
cfy recover [options] -s SNAPSHOT_PATH
TO BE
cfy recover [options] -s SNAPSHOT_PATH -f
Please check it and thanks!
=> Add a required flag in cli/recover.md

content/cli/plugins.md
It provides a wrong flag in usage for the cfy plugins delete command.
AS IS 
cfy plugins delete [options] -s SNAPSHOT_ID
TO BE
cfy plugins delete [options] -p PLUGIN_ID
Please check it and thanks!
=> Modify a wrong flag in cli/plugins.md

content/cli/plugins.md
It can not access the wagon via the link in plugins.md and fix the link to visit the wagon in GitHub directly.
AS IS
({{< relref "http://github.com/cloudify-cosmo/wagon" >}})
TO BE
(https://github.com/cloudify-cosmo/wagon)
Please check it and Thanks!
=> Fix a link for wagon in plugins.md

content/cli/overview.md
It is a comments for config_file in CLI/overview.md which breaks a word.
AS IS
`config <https://github.com/cloudify-cosmo/cloudify-cli/blob/3.4/cloudify_cli/resources/config.yaml>`_ file 
TO BE
`config_file <https://github.com/cloudify-cosmo/cloudify-cli/blob/3.4/cloudify_cli/resources/config.yaml>` 
Please check it and Thanks!
=> Modify a comments for config_file in overview.md

content/manager/snapshots.md
Fix a link for snapshots in snapshots.md which accesses the snapshots page failed 
AS IS
link ({{< relref "cli/reference.html" >}})
TO BE
link ({{< relref "cli/snapshots.md" >}})
Remove the redundant signs as follows:
AS IS
plugins/ - Folder containing all plugins uploaded to the Manager.
snapshot-credentials/ - .pem key files for all installed applications VMs.
blueprints/ - Extracted blueprints uploaded to the Manager.
uploaded-blueprints/ - Blueprints uploaded to the Manager as .tar.gz files.
TO BE
plugins - Folder containing all plugins uploaded to the Manager.
snapshot-credentials - .pem key files for all installed applications VMs.
blueprints - Extracted blueprints uploaded to the Manager.
uploaded-blueprints - Blueprints uploaded to the Manager as .tar.gz files.
Please check them …
=> Fix a link for snapshots and remove unused signs

content/manager/upload-blueprint.md
Fix a link for deploy in upload-blueprint.md which can not access the create-deploymentpage.
AS IS
deploy ({{< relref "manager/bootstrapping.md" >}})
TO BE
deploy ({{< relref "manager/create-deployment.md" >}})
Please check it and merge it to 3.5.0-build and 3.4.1-build 
Thanks!
=> Fix a link for deploy in upload-blueprint.md

content/intro/blueprints.md
Modify version for dsl and types. in blueprints.md. It should be cloudify_dsl_1_3 for tosca_definitions_version and  import http://www.getcloudify.org/spec/cloudify/3.4/types.yaml in v3.5.0
=> Modify version for dsl and types in blueprints.md

content/manager/bootstrapping.md
Fix a link for prerequisites in bootstrapping.md which can not access the prerequisites page.
AS IS
prerequisites ({{< relref "manager/bootstrapping.md" >}}) 
TO BE
prerequisites ({{< relref "manager/prerequisites.md" >}}) 
Please check it and merge it to 3.5.0-build and 3.4.1-build 
Thanks!
=> Fix a link for prerequisites in bootstrapping.md

content/plugins/gcp.md
Some rough edges still - mostly that it turns out the GlobalAddress > Http(s)Forwarder > BackendService > ? > InstanceGroup > Instance stuff is a lot more complicated than I gave it credit for and I don't 100% understand it yet, so the corresponding bits of the docs aren't done yet either :(
My local docs.getcloudify.org-site instance is acting up and making the GCP page disappear, so I haven't been able to proof all of the formatting.
(types generated using https://github.com/funkyHat/cfy-generated-docs-poc)
=> Add gcp docs

content/plugins/vsphere.md
Covers code changes for:
https://cloudifysource.atlassian.net/browse/CFY-2415 (allow specifying particular hypervisors on which to deploy)
https://cloudifysource.atlassian.net/browse/CFY-2805 (allow specifying particular clusters on which to deploy)
https://cloudifysource.atlassian.net/browse/CFY-2704 (allow specifying particular datastores on which to deploy)
#62 (don't deploy to hosts which don't have specified resource pool)
https://cloudifysource.atlassian.net/browse/CFY-5890 (don't try to deploy on disconnected datastores)
https://cloudifysource.atlassian.net/browse/CFY-5337 (don't try to deploy on disconnected hosts NB: Does not fix the issue of trying to deploy on unlicensed/license-expired hosts)
https://cloudifysource.atlassian.net/browse/CFY-1281 (improve error messages when …
=> Hypervisor selection documentation for 3.4 docs

content/plugins/vsphere.md
Covers code changes for:
https://cloudifysource.atlassian.net/browse/CFY-2415 (allow specifying particular hypervisors on which to deploy)
https://cloudifysource.atlassian.net/browse/CFY-2805 (allow specifying particular clusters on which to deploy)
https://cloudifysource.atlassian.net/browse/CFY-2704 (allow specifying particular datastores on which to deploy)
#62 (don't deploy to hosts which don't have specified resource pool)
https://cloudifysource.atlassian.net/browse/CFY-5890 (don't try to deploy on disconnected datastores)
https://cloudifysource.atlassian.net/browse/CFY-5337 (don't try to deploy on disconnected hosts NB: Does not fix the issue of trying to deploy on unlicensed/license-expired hosts)
https://cloudifysource.atlassian.net/browse/CFY-1281 (improve error messages when …
=> Hypervisor selection documentation for current docs

content/plugins/openstack.md
This is incorrect as of OpenStack plugin v2.0 onwards
=> Removed incorrect statement about keystone v2

content/apis/rest-service.html
http://docs.getcloudify.org/api/v2.1
the old link still works, but it will eventually be redirected to the API v3 docs.
=> Update API docs link for 3.4.0

content/apis/rest-service.html
http://docs.getcloudify.org/api/v2.1
the old link still works, but it will eventually be redirected to the API v3 docs.
=> Update API docs link for 3.4.1

content/apis/rest-service.html
http://docs.getcloudify.org/api/v2.1
the old link still works, but it will eventually be redirected to the API v3 docs.
=> Update API docs link for 3.4.2

content/apis/rest-service.html
http://docs.getcloudify.org/api/v2
=> Update API docs link for 3.3.1

content/apis/rest-service.html
http://docs.getcloudify.org/api/v2
=> Update API docs link for 3.3.0

content/apis/rest-service.html
http://docs.getcloudify.org/api/v3
=> CFY-6712. Update API docs link for 4.0.0

content/installation/bootstrapping.md
It's 5671 starting 4.x (and SSL-protected)
=> Fix RabbitMQ port

content/installation/from-packages.md, content/installation/uninstall-cloudify-cli.md, content/installation/upgrade_4-0-0.md, content/intro/cloudify-manager.md, content/intro/doc-info.md, content/intro/evaluating-cloudify.md
Primarily updates to version numbers in the intro pages. Please take a look at uninstalling Cloudify, where the teardown section has been added, to ensure that it is accurate.
=> minor fixes to 4.1 version

content/plugins/gcp.md
Should be added with updated keys once https://cloudifysource.atlassian.net/browse/GCP-41 is done
=> (temporarily) remove secrets section from GCP page

content/blueprints/spec-plugins.md, content/cli/deployments.md, content/manager/create-deployment.md
I have added this in the **blueprints > plugins** and **cli > deployments** pages, and have added a pointer from the **manager > creating a deployment** page to the CLI page. 
After this is approved and merged into the 4.1 documentation, I will add it to the 4.2 branch.
**Is this also relevant for 4.0?
=> Adding skip-plugins-validations

content/manager_webui/custom-widgets.md, content/manager_webui/overview.md
Updated docs to include information about "permissions" field in Widgets definition along with a new paragraph discussing the 'Community' edition of Cloudify Web UI
You can preview the changes here:
**Custom Widgets**
http://stage-docs.getcloudify.org/docathon-UI-opensource-custom-widgets/manager_webui/custom-widgets/
**Open Source**
http://stage-docs.getcloudify.org/docathon-UI-opensource-custom-widgets/manager_webui/overview/
=> Docathon - [UI] Open Source, Custom Widgets Permissions

content/installation/bootstrapping.md
`python-virtualenv` package on CentOS 7 installs pip 1.4.1 which is positively ancient, and can't cope with some of the wheels in our wagons.
=> add `pip install --upgrade pip` to "offline" installation instructions

content/cli/secrets.md
In this PR, the documentation of the create secret command is updated to describe the new `upsert` flag.
Related: cloudify-cosmo/cloudify-cli#710
=> CFY-7562 Add -u/--update-if-exists flag to secrets create command

content/manager/create-deployment.md
Deployment creation command shouldn't be with the -d flag anymore: cfy deployments create -b <BLUEPRINT_NAME> <DEPLOYMENT_NAME> --inputs </path/to/your/inputs.yaml​>
=> Create deployment command

content/manager/execute-workflow.md
Deployments output command should be without the -d flag: cfy deployments outputs nodecellar
=> Remove -d flag from deployments command

content/manager/upload-blueprint.md
Upload blueprint command should be without the -p flag. 
It can be uploaded either from an unzip file which you pass with the blueprint upload command: cfy blueprints upload -b BLUEPRINT_NAME  BLUEPRINT_YAML_FILE_PATH
Or by passing the command with -n flag that will indicate the blueprint's file in the zip file (can be zip from URL or from the VM)
=> Upload blueprint command

content/apis/widgets-components.html, content/manager_webui/custom-widgets.md
Please review: http://stage-docs.getcloudify.org/STAGE-693
Widgets Components API Reference uploaded. Available here: http://docs.getcloudify.org/widgets-api/4.3.0/. *STAGE-692 - Customize components documentation* not yet implemented.
Added link(s) to Widgets Components API Reference:
- in left navigation bar 
- in [Manager UI Reference > Creating Custom Widgets](http://stage-docs.getcloudify.org/STAGE-693/manager_webui/custom-widgets/) page
Maybe there's possibility to make that link contain variable for version not to update it manually each release? Can we take `"version": "4.3.0",` from `package.json` somehow?
=> STAGE-693 - Add links in official documentation

content/plugins/openstack.md
Old example doesn't work in case of two or more ports connected to one instance and joined in one policy group.
=> Change cloudify.openstack.nodes.Port example

.gitignore, content/manager_webui/custom-widgets.md, content/manager_webui/overview.md
In Widget Settings table:
* Added *Required* column 
* Added missing settings (`hasTemplate` and `hasStyle`)
* Sorted settings in alphabetical order
That fix is for 4.3.
=> Updated Widget Settings table

content/manager_architecture/components.md
Moved from https://github.com/cloudify-cosmo/docs.getcloudify.org/pull/680 by uriwygo in 4.1.0
=> RabbitMQ port default changed

.circleci/config.yml
- Build includes Google Tag Manager for production only
- Deploy pushes production to version directories, master to staging/dev and others to staging/{branch}
=> Implement split build and deploy

content/about/manager_architecture/security.md
I've removed the security auditing section as we don't have it in Cloudify 4.x
=> Removed the security auditing branch

content/working_with/manager/service-logs.md
Removed the security auditing branch as it is not relevant for Cloudify 4.x
=> Removed the security auditing section

content/install_maintain/installation/installing-cluster.md
It doesn't use overall CA path.
This is tested eg. in the cloudify-manager-install's CI, with this DB config:
https://github.com/cloudify-cosmo/cloudify-manager-install/blob/master/.circleci/cluster/db_config.yaml
=> Installing cluster: postgres uses postgres_ca_cert_path

static/css/nucleus.css, static/theme-flex/style.css
- scrollbar is attached only to content pane not to the whole site (with header and footer)
- live site: https://docs.cloudify.co/staging/anchored-headers-fix
=> CY-1458 - Improved headers styling and content part scrolling

support/cloudify-vnf-story/upload-secrets.sh
The idea is to allow this repo to store supporting files (a script in this case) for documents external to the traditional getcloudify docs), per Ido's suggestion.
=> added support dir and support script

content/working_with/console/widgets/highAvailability.md
After recent change - https://github.com/cloudify-cosmo/cloudify-stage/pull/901 - there is no widget data fetching in Cluster Status widget. Data is fetched from application state and cluster-status is being fetched periodically by the application itself, not the widget.
=> Remove Cluster Status widget configuration info

content/working_with/workflows/resuming.md
This makes the high-level overview of resuming support also link to the
more specific pages about creating operations and workflows that can
support the feature.
Thanks @isaac-s for being the test subject :)
=> Resume docs: link to operation and workflow pages

content/working_with/official_plugins/Infrastructure/gcp.md
added in gcp plugin documentation  the option to provide the gcp credentials as json
=> CY-2454-Support-GCP-credentials-config-as-one-big-json-string

content/install_maintain/installation/manager-image.md
- drop a useless note
- explain flags to `docker run`
- add an explanation for the used `docker run` flags
- add a note about configuring the manager
- explain how to get/reset credentials
=> Running manager on docker: add more explanations

layouts/partials/version.html
Add current relative URL to new version link on docs version change.
Now, instead of opening main page for the specific version you are redirected to specific version + current page link.
=> Improve documentation version dropdown

content/install_maintain/manager_architecture/security.md
`cfy ssl` is no longer a thing, use just `cfy_manager configure`
instead.
Also update some comments about replacing certs - use the replace
commands under `cfy certificates` instead.
=> RD-759 Update ssl comments in the manager installation docs

content/developer/writing_widgets/widgets-components.md
This PR updates the version of `cloudify-ui-components` to 2.3.0
Component docs: https://docs.cloudify.co/ui-components/2.3.0
Release notes: https://github.com/cloudify-cosmo/cloudify-ui-components/releases/tag/v2.3.0
=> RD-1230 Update cloudify-ui-components version to 2.3.0

content/developer/writing_widgets/widgets-components.md
The latest version of cloudify-ui-components that will be used by stage is 2.4.1. Here's the updated link to the storybook:
https://docs.cloudify.co/ui-components/2.4.1/
=> RD-1222 Update ui-components version to 2.4.1

content/cli/orch_cli/plugins.md
* Change `--all` to `--all-blueprints` for clarity
* Add `--all-tenants` flag for cfy plugins update and make `-a` be the
short form for `--all-tenants`, not `--all-blueprints`
=> RD-1455 Clarify plugins update --all parameter

content/working_with/console/widgets/filters.md
Added operator mapping UI/API/CLI to Filters widget description (https://docs.cloudify.co/staging/RD-2318/working_with/console/widgets/filters):
=> RD-2318 - Improve Filters widget description

content/cli/orch_cli/filter-rules.md
This PR copies the filter-rules tables from [here](https://github.com/cloudify-cosmo/docs.getcloudify.org/pull/1830) to the filter-rules documentation with slight modification - replacing "deployment" with "resource".
=> RD-2515 Add table to filter-rules docs

content/working_with/console/widgets/filter.md
This PR describes the incompatibility between the Resource Filter widget and the Deployments View widget. See the description of RD-1829 for more information about the technical incompatibilities.
There is already a similar note in the description of the Deployments View widget: https://docs.cloudify.co/6.0.0/working_with/console/widgets/deploymentsview/#filtering-deployments
Once this PR is merged, I will update the readme in cloudify-stage in a separate PR
Staging: https://docs.cloudify.co/staging/RD-1829-explain-incompatibility-resource-filter-and-deployments-view/working_with/console/widgets/filter/
=> RD-1829 Describe incompatibility between Resource Filter and Deployments View

content/developer/writing_widgets/widgets-components.md
This PR changes the link to point to the latest version of https://github.com/cloudify-cosmo/cloudify-ui-components (released after https://github.com/cloudify-cosmo/cloudify-ui-components/pull/75 was merged)
https://docs.cloudify.co/ui-components/2.5.0
=> RD-1787 Upgrade cloudify-ui-components version to 2.5.0

content/developer/writing_widgets/widgets-components.md
There's a new release of UI components:
https://github.com/cloudify-cosmo/cloudify-ui-components/releases/tag/v2.6.0
https://docs.cloudify.co/ui-components/2.6.0
=> RD-2789 Upgrade UI components link to point to 2.6.0

content/developer/writing_widgets/widgets-components.md
Reverts cloudify-cosmo/docs.getcloudify.org#2029 as we need to figure out why there's bundle size increase in `cloudify-stage` coming from `cloudify-ui-components` v2.9.2.
=> Revert "Update version of cloudify-components to 2.9.2"

content/developer/writing_widgets/widgets-components.md
Provides update of `ui-components-link`. The same PR as https://github.com/cloudify-cosmo/docs.getcloudify.org/pull/2029.
=> RD-3496 Update ui-components-link to v2.9.2

content/working_with/console/widgets/userGroups.md
This change is related to the discussion which took place [here](https://github.com/cloudify-cosmo/cloudify-stage/pull/1682#discussion_r759250926)
The result of the conversation was that the `LDAP` is incorrectly prepended with the `the` word
=> RD-3477 Removed gramatically incorrect prepending LDAP with 'the'

content/working_with/workflows/creating-your-own-workflow.md
When running a deployment-modification in a workflow, remember to
refresh instances, if you wish to use them.
=> CYBL-733 Custom workflows: note about refresh_instances

content/cli/orch_cli/blueprints.md, content/cli/orch_cli/deployments.md, content/cli/orch_cli/secrets.md
`cfy blueprints set-owner`, `cfy deployments set-owner`, `cfy secrets set-owner` can be called with optional `-t tenant_name` parameter now.
=> RD-3983 Set-owner now with -t tenant_name option

content/developer/writing_widgets/widget-backend.md
The doc contains reference to https://github.com/cloudify-cosmo/Cloudify-UI-Widget-boilerplate/tree/master/widgets/backendWidget which is pretty outdated. There are tickets like RD-229 and RD-231 which should address this, so I assume no further action is required ATM.
=> RD-1923 Updated widget backend development doc after adding support for TS

content/developer/writing_widgets/development-methods.md, content/developer/writing_widgets/useful-links.md, content/developer/writing_widgets/widget-backend.md, content/working_with/console/customization/edit-mode.md, content/working_with/console/widgets/filters.md
As https://github.com/cloudify-cosmo/Cloudify-UI-Widget-boilerplate is not maintained, I removed all references to it.
Improved https://github.com/cloudify-cosmo/cloudify-stage support for widgets development within https://github.com/cloudify-cosmo/cloudify-stage/pull/1845.
=> RD-4317 Update writing widgets documentation

content/developer/blueprints/spec-workflows.md
Currently only describe the simplest rule, `available`. Further rules
will be described when they're implemented
=> RD-4616 workflows: note about availability_rules

content/developer/blueprints/spec-plugins.md
Document the `credentials` DSL node, introduced in Cloudify DSL 1.5
=> RD-5831 plugin properties and properties_description DSL change

content/cli/orch_cli/deployments.md, content/working_with/manager/update-deployment.md, content/working_with/workflows/built-in-workflows.md
* Remove a note about a 3.4-related issue
* Update the document into to talk about drift/status
* remove the types.yaml comment
it's not true anymore, update is a built-in workflow
* Describe the flow
* Update the notes about skipping parts of the workflow
* remove pointless "existing resources" paragraph
yes the blueprint must already exist, and the things that changed in it, have changed
* Describe implementing check_drift & update
* move "unsupported" to after "supported"
* update the note on plugins
Plugins are installed on first use!
* add a note about --drift-only
* markdown syntax updates
Now no warnings in my editor :)
* s/eg./e.g./
That is the way to write it indeed
Co-authored-by: glukhman <47591609+glukhman@users.noreply.github.com>
* Add a few "the"
Co-authored-by: glukhman …
=> RD-5992 New deployment-update docs (#2369)

content/working_with/workflows/parameters.md
Updated page rendered: https://docs.cloudify.co/staging/RD-6091-workflows-fix/working_with/workflows/parameters/
=> RD-6091 `-w` not required before WORKFLOW_ID

content/working_with/manager/create-deployment.md, content/working_with/manager/upload-blueprint.md, content/working_with/official_plugins/Infrastructure/vcloud.md
* vCloud plugin documentation updated to clearly state that plugin is only for Vmware vCloud Air. vCloud Air seem not to be anymore (since 2017) in Vmware product portfolio. Plugin does not support Vmware current vCloud Director, so documentation has to define that for the reader.
* Update create-deployment.md
* Update upload-blueprint.md
Co-authored-by: Tomi Weckström <tomi.weckstrom@teliacompany.com>
=> vCloud plugin is only for vCloud Air, not for vCloud Director (#1197)

content/developer/writing_widgets/widget-definition.md
Documentation update for changes introduces in https://github.com/cloudify-cosmo/cloudify-stage/pull/2330.
There's major update of the screenshots (e.g. widget screenshots) in documentation planned (after theming changes), so I'll leave it for RD-6607.
=> RD-6490 Update `color` parameter description in widget definition

content/working_with/manager/update-deployment.md
Explain what does it mean for values to be false or true, as suggested by @kfrukacz-gs
=> Deployment update: explain check_drift return value evaluation

content/working_with/workflows/built-in-workflows.md
When check_drift fails, of course we must reinstall the node, but this was not mentioned anywhere before.
=> CYBL-2004 Deployment update: note what happens when check_drift fails

content/cli/orch_cli/executions.md
This is the CLI for changing the concurrency setting of an exc-group.
=> RD-7042 CLI docs: `cfy exec groups set-concurrency`
