cloudify-cosmo/docs.getcloudify.org

content/guide/dsl-spec-general.md

Related to https://github.com/cloudify-cosmo/getcloudify.org/pull/420/files

Fixed typo

---

content/manager-blueprints-openstack.md
content/manager/manager-recovery.md
content/manager/watchdog.md

Conflicts:
content/manager/watchdog.md

CFY-3762 updated recovery and watchdog doc

---

content/composer/installation.md

took out any reference of "blueprint composer"

changed blueprint composer to cloudify composer

---

content/installation/from-packages.md
content/plugins/openstack.md
content/plugins/overview.md
content/plugins/using-plugins.md

CFY-4743 update openstack plugin compatibility section
CFY-4719 modify installation page layout

CFY-4721 modified using-plugins page title

---

content/composer/available-actions.md
content/composer/blueprint-creation.md
content/composer/overview.md

Conflicts:
content/composer/available-actions.md

fix(overview) fix according to noak review.

---

content/plugins/aws.md
content/plugins/chef.md
content/plugins/diamond.md
content/plugins/docker.md
content/plugins/fabric.md
content/plugins/host-pool.md
content/plugins/openstack.md
content/plugins/puppet.md
content/plugins/script.md
content/plugins/vcloud.md
content/plugins/vsphere.md

CFY-5050 - added prerequisites for OpenStack plugin

---

content/plugins/aws.md

removing the stuff related to 331

---

content/intro/getting-started.md

Fixed a typo - variaty should be variety

CFY-5268-Fix-typo

---

content/intro/blueprints.md

Remove the repeating content in Blueprint.md, which describes the same content.
Please check it.
Thanks!

Remove the repeating content in Blueprint.md

---

content/cli/blueprints.md

Add some missed  required flags in blueprints.md，which may be helpful to use these command.
Please check them and thanks!

Add the missed required flags in blueprints.md

---

content/intro/cloudify-manager.md

link was 404ing --> Changed to first part in manager section.

Fixed broken link

---

content/error404.md

Edited to Cloudify Blog Link

---

content/cli/deployments.md
content/cli/uninstall.md
content/cli/upgrade.md

Fix the assignment mistake int flags which the signe  '='  is missed.
Please check it and thanks!

Fix the assignment mistake in flags

---

content/manager/bootstrapping.md

Fix URL for bootstrapping on OpenStack

---

content/installation/from-script.md

Makes the virtualenv unwritable to anyone but root

Avoid using `sudo`

---

content/plugins/openstack.md

Add version compatibility & note about keystone URL

OPENSTACK-41 support for Liberty & Mitaka

---

content/manager/implement-multi-tenancy.md

I have removed the incorrect sentence from the page as requested. Please verify and approve so that I can merge this into the main branch.

removing incorrect statement from page

---

content/cli/blueprints.md
content/cli/bootstrap.md
content/cli/clusters.md
content/cli/deployments.md
content/cli/dev.md
content/cli/events.md
content/cli/executions.md
content/cli/groups.md
content/cli/init.md
content/cli/install.md
content/cli/logs.md
content/cli/maintenance-mode.md
content/cli/node-instances.md
content/cli/nodes.md
content/cli/overview.md
content/cli/plugins.md
content/cli/profiles.md
content/cli/rollback.md
content/cli/secrets.md
content/cli/snapshots.md
content/cli/ssh.md
content/cli/status.md
content/cli/teardown.md
content/cli/tenants.md
content/cli/uninstall.md
content/cli/upgrade.md
content/cli/use.md
content/cli/usergroups.md
content/cli/users.md
content/cli/workflows.md

This branch fixes the issues with italics incorrectly appearing in code snippets that included underscores.

Chana docs real cli fix

---

content/intro/installation.md

correct link is http://getcloudify.org/downloads/get_cloudify.html

updated DL link again

---

content/blueprints/overview.md
content/blueprints/spec-imports.md
content/blueprints/spec-versioning.md
content/installation/from-packages.md
content/installation/from-source.md
content/intro/blueprints.md
content/manager/getting-started.md

updated a bunch of links to 3.3.1 to match latest version

Updating versions

---

content/agents/overview.md

Add sudo prerequisite for agents

---

content/manager/bootstrapping.md

Using `sudo` is mandatory if bootstrapping using a non-root user and using `--install-plugins`.

Update sudo info

---

content/plugins/vsphere.md

vSphere plugin has been added to open source CFY since 3.4

removed the part about commercial of vSphere

---

content/plugins/openstack.md

and remove mention of openstack blueprint

Change default config path

---

content/installation/uninstall-cloudify-cli.md

Changed a heading from _Removing Cloudify Manager from the VM_ to *_Deleting Cloudify Manager from a VM_*

changed Removing CFY from VM to DELETING

---

content/cli/ldap.md
content/installation/bootstrapping.md

This PR covers changes that were made to "Installing Cloudify in an Offline Environment" links, and a fix related to JIRA CFY-7034.

Chana 4.1 updates1

---

content/plugins/gcp.md

Just adding the GCP plugin topic back into the main branch.

readding GCP plugin to branch

---

content/manager_webui/default-widgets-ref.md

I have incorporated the changes into the default widgets configuration topic. Please review and approve. I will then add it to the 4.2 branch and update it specific to the 4.2 release.

Chana widget updates

---

content/manager_architecture/components.md

Removed reference to elasticsearch and grafana

Removed unused components

---

content/manager/high-availability-clusters.md

First pass over the HA docs, removing the obviously wrong statements.

HA docs: update the services list to be current with 4.2

---

content/cli/tenants.md

In this PR, the documentation for `cfy tenants` is updated to take roles into account.

CFY-7480. Update "Command Line Interface -> Tenants" to take roles into account

---

content/plugins/script.md

Also changed some links to refer to 4.2 instead of 3.3

CFY-7570: added PS 64bit doc

---

content/plugins/vsphere.md

vSphere Environment update

---

content/blueprints/spec-outputs.md

Changed:
- tosca_definitions_version,
- import,
- REST call,
- CLI

Update Blueprint/outputs page 

---

content/manager/create-deployment.md

Add reference to deployment inputs being provided in a YAML file

Deployment inputs in a YAML file

---

content/cli/usergroups.md

Add an example for the -l flag, and update master.

Talisela patch 4

---

content/plugins/azure.md

These are updates to the Azure docs that cover additions from 1.5.0 - 1.5.1.1.

update azure docs for 1.5.1.1

---

content/manager/user-management.md

Removing a wrong reference to the UI docs for LDAP integration info (which is actually later on this page).

Removing a wrong reference

---

content/cli/blueprints.md
content/cli/deployments.md
content/cli/init.md
content/cli/node-instances.md
content/cli/nodes.md
content/cli/plugins.md
content/cli/secrets.md
content/cli/snapshots.md
content/cli/tenants.md
content/cli/usergroups.md
content/cli/users.md

CY-130 add documentation for the search parameter in list commands

---

content/blueprints/import-resolver.md

We need to have someone from R&D review this. I'm not sure if the information here is very old or very new. But it is surely very unclear and incomplete.

Docs Check-Up

---

content/manager_webui/custom-widgets.md

Changes:
* in Widget Structure section added `readme.md` file,
* in Widget Settings table added new fields - `hasReadme` and `helpUrl`.
This PR bases on #689 => #689 shall be merged first to `master`, then `next` shall be updated from `master` and after that this PR can be merged.

CY-144 - Update documentation (Stage Help)

---

content/cli/users.md

These changes, once approved, should also be applied to 4.2 and 4.1 documentations.

Update users for 4.3.

---

content/manager/user-management.md

As before we only regarded the LDAP connectivity

Add "Managing users in Cloudify Manager" paragraph

---

content/plugins/utilities.md

These bullets don't look right. Here's the fix.

fix bullets in utilities plugin docs

---

content/kubernetes/provider.md

List the filenames in the Kubernetes Provider.

Kubernetes Provider: List Filenames.

---

content/kubernetes/provider.md

These secrets are not necessary.

Remove Requirement for funky secrets.

---

content/working_with/manager/okta_authentication.md

fix image link

---

content/working_with/manager/resource-visibility.md

Uriwygo patch 1

---

content/cli/maint_cli/init.md
content/cli/maint_cli/profiles.md
content/cli/orch_cli/plugins.md
content/cli/orch_cli/status.md

Updated:
- cfy init
- cfy plugins
- cfy profiles
- cfy status

Adopt a page 4.4

---

content/working_with/official_plugins/azure.md

* Update azure.md
* Update azure.md

Update azure.md (#947)

---

content/working_with/official_plugins/script.md

Also formatted the process configuration options section as a table.

CY-781: doc updates

---

content/developer/blueprints/spec-intrinsic-functions.md

CY-884 Add support for nested intrinsic function calls

---

content/ops_guides/backup_restore_guide.md

Fix wrong snapshot download endpoint in the docs

Fix snapshot curl download endpoint

---

content/developer/blueprints/spec-capabilities.md
content/developer/blueprints/spec-intrinsic-functions.md

link capabilities docs with get_capability

---

content/developer/blueprints/spec-capabilities.md
content/developer/blueprints/spec-intrinsic-functions.md

* link capabilities docs with get_capability

link capabilities docs with get_capability (#1028)

---

content/cli/orch_cli/deployments.md
content/cli/orch_cli/plugins.md
content/developer/blueprints/spec-imports.md
content/developer/writing_plugins/creating-your-own-plugin.md
content/working_with/manager/update-deployment.md

- Add the documentation of the don't update plugins flag in deployment
udpates

CY-1060 Add plugins update info

---

content/bestpractices/vnfguide.md
static/scripts/upload-secrets.sh

* Create upload-secrets.sh
* Update vnfguide.md

Adding DeWayne's script for secret upload (#1119)

---

static/theme-flex/style.css

* Improved headers styling and content part scrolling.
* Changed headers padding only for content pane

CY-1458 - Improved headers styling and content part scrolling (#1148)

---

content/working_with/service_composition/component.md

Outputs is not in use in Component.

Component - removing outputs

---

content/developer/debugging/debugging-cloudify-workers.md

Adding a debugging note to inform how to use remote debugger with Cloudify Manager and agents

Add debugging note

---

content/install_maintain/installation/installing-cli.md

Links to download page were 404 url

fixed links to DL page

---

content/bestpractices/vnfguide.md

update the versions to 5.0.0-3 and added section for components service e2e

updates to 5.0.0

---

content/working_with/official_plugins/Infrastructure/openstackv3.md

update to include OS release compatibility

Add OS release compatibility details for OS plugin v3

---

content/working_with/official_plugins/Infrastructure/openstack.md
content/working_with/official_plugins/Infrastructure/openstackv3.md

update OS plugin v2 documentation with OS compatibility details.

Update plugin v2 OS compatibility 

---

content/working_with/official_plugins/Infrastructure/azure.md

Added AKS Cluster to Azure Documentation `5.0.5-build`

Azure-AKS-5.0.5-build

---

content/working_with/official_plugins/Orchestration/ansible.md
content/working_with/official_plugins/Orchestration/terraform.md

Updates to Ansible and Terraform for docs `5.0.0-build`

CY-2444-Update-Ansible-Terraform-documentation-5.0.0

---

content/working_with/official_plugins/Infrastructure/aws.md

Added EKS Cluster to AWS plugin `5.0.5-build`

AWS-EKS-Docs

---

content/working_with/official_plugins/Infrastructure/aws.md

Added EKS Cluster to AWS plugin docs `5.0.0-build`

AWS-EKS-5.0.0

---

content/working_with/official_plugins/Infrastructure/openstackv3.md

Added Designate to Openstack v3 plugin documentation

Desingate-Openstack-Doc-Update

---

content/working_with/official_plugins/Infrastructure/openstackv3.md

Added Designate Support to openstack v3 doc `5.0.5-build`

Designate-Openstack-Doc-Update-5.0.5-build

---

content/working_with/official_plugins/Infrastructure/openstackv3.md

Added Designate Support to openstack v3 docs `5.0.0-build`

Desingate-Openstack-Doc-Update-5.0.0-build

---

content/working_with/official_plugins/Orchestration/ansible.md
content/working_with/official_plugins/Orchestration/terraform.md

Updates to Ansible and Terraform for docs `5.0.5-build`

CY-2444-Update-Ansible-Terraform-documentation-5.0.5

---

content/working_with/official_plugins/Orchestration/ansible.md
content/working_with/official_plugins/Orchestration/terraform.md

Added some updates on Ansible and Terraform docs

CY-2444-Update-Ansible-Terraform-documentation

---

content/working_with/official_plugins/Orchestration/terraform.md

Update Terraform Plugin Doc on master

CY-2478-Update-Terraform-Plugin-Doc

---

content/working_with/official_plugins/Orchestration/terraform.md

Updated Terraform plugin docs on `5.0.0`

CY-2478-Update-Terraform-Plugin-Doc-5.0.0-build

---

content/working_with/official_plugins/Orchestration/terraform.md

Updated Terraform plugin doc on branch `5.0.5-build`

CY-2478-Update-Terraform-Plugin-Doc-5.0.5-build

---

content/cli/maint_cli/snapshots.md
content/ops_guides/backup_restore_guide.md

More detailed description of restoring scheduled executions from
snapshots.

CY-2493 Add description of scheduled execs restore

---

content/cli/orch_cli/plugins.md

Added new parameter (`-i` or `--icon-path`) to `cfy plugin upload` command.

CY-2563 Update description of cfy plugin upload

---

content/install_maintain/installation/installing-manager.md

AWS image is no longer supported
@ofercloudify

removed AWS reference

---

content/trial_getting_started/_index.md
content/trial_getting_started/examples/_index.md
content/trial_getting_started/examples/automation_tools/_index.md
content/trial_getting_started/examples/automation_tools/aws_cloudformation_basics.md
content/trial_getting_started/examples/automation_tools/aws_terraform_basics.md
content/trial_getting_started/examples/automation_tools/azure_arm_basics.md
content/trial_getting_started/examples/basic/_index.md
content/trial_getting_started/examples/basic/aws_basics.md
content/trial_getting_started/examples/basic/azure_basics.md
content/trial_getting_started/examples/basic/gcp_basics.md
content/trial_getting_started/examples/basic/openstack_basics.md
content/trial_getting_started/examples/first_service/_index.md
content/trial_getting_started/examples/first_service/aws_hello_world_example.md
content/trial_getting_started/examples/first_service/azure_hello_world_example.md
content/trial_getting_started/examples/first_service/gcp_hello_world_example.md
content/trial_getting_started/examples/first_service/local_hello_world_example.md
content/trial_getting_started/examples/first_service/openstack_hello_world_example.md
content/trial_getting_started/examples/multi_cloud/multi-cloud_JBoss_example.md
content/trial_getting_started/examples/multi_cloud/multi-cloud_nodejs_example.md
content/trial_getting_started/set_trial_manager/_index.md
content/trial_getting_started/set_trial_manager/cli_install.md
content/trial_getting_started/set_trial_manager/download_community.md
content/trial_getting_started/set_trial_manager/hosted_trial.md
content/trial_getting_started/set_trial_manager/trial_install.md
content/trial_getting_started/trial_faq.md
static/images/ui/login/_index.md

Some Formatting, fixes and re-ordering of the getting started & trial

CY-2491-Documentation-Fixes

---

content/working_with/official_plugins/Configuration/kubernetes.md
content/working_with/official_plugins/Infrastructure/gcp.md

fixed eks example and started write aks example documentation
added aks doumentation and gcp cluster nodes to gcp documentation
fix typos in kubernetes and gcp documentation
added more resources to doc and file resources defenition guide
review fixes
notes fixes

added eks and gke examples documentation

---

content/working_with/official_plugins/Orchestration/docker.md

CY-2714-Docker-Plugin-Doc

---

content/working_with/official_plugins/Orchestration/docker.md

CY-2714-Docker-Plugin-Doc-5.0.0

---

content/working_with/official_plugins/Orchestration/docker.md

CY-2714-Docker-Plugin-Doc-5.0.5

---

content/working_with/official_plugins/Orchestration/docker.md

CY-2714-Docker-Plugin-Doc-Fixes

---

content/working_with/official_plugins/Orchestration/docker.md

CY-2714-Docker-Plugin-Doc-5.0.0-Fixes

---

content/working_with/official_plugins/Orchestration/docker.md

CY-2714-Docker-Plugin-Doc-5.0.5-Fixes

---

content/cli/orch_cli/events.md

With CY-2725 there are changes introduced to `cfy events list` and
`cfy events delete`.  This patch updates documentation for those.

Describe changes introduced to `cfy events`

---

content/cli/orch_cli/events.md

This is a description for the functionality introduced in https://github.com/cloudify-cosmo/cloudify-cli/pull/1086

CY-2806 Allow Unix time in cfy events

---

config.toml
content/trial_getting_started/examples/basic/aws_basics.md
content/trial_getting_started/examples/basic/azure_basics.md
content/trial_getting_started/examples/basic/gcp_basics.md
content/trial_getting_started/examples/basic/openstack_basics.md
content/trial_getting_started/examples/first_service/local_hello_world_example.md
layouts/partials/mini-toc.html
layouts/shortcodes/lower.html

* Templatizing and fixing ToC to guarantee anchor links work - even with duplicate names
* Updating OpenStack doc
* initial first_service templatizing
* blueprint name change
This is basically a bunch of changes to support templatizing these pages. You'll find a lot of new variables in the config file and at the top of some of the page files. So in the future, if we need to change a link or common name, we can just do it once and it will propagate.

Template / variable updates for consistency

---

.circleci/config.yml

Update hugo image

---

content/trial_getting_started/set_trial_manager/download_community.md

old link was 404'd
@ofercloudify

fixed link to difference between versions

---

config.toml
content/trial_getting_started/set_trial_manager/download_community.md
content/trial_getting_started/set_trial_manager/getting-started-with-cloudify-docker-and-cli.md
content/trial_getting_started/set_trial_manager/trial_install.md

Fixed some minor areas that came out through the last discussion with Dor related to the clarity of the use of the CLI via docker.

Minor cli related updates

---

content/trial_getting_started/set_trial_manager/download_community.md

We didn't have it on the page.

added default login info

---

layouts/shortcodes/field.html

CY-3486 - Update field shortcode to remove whitespaces from the output

---

content/working_with/official_plugins/Orchestration/helm.md

do not use executable path

---

content/working_with/official_plugins/Orchestration/helm.md

all fix
Signed-off-by: AdarShaked <adar@cloudify.co>
markdown fixes
review fixes

add documentation for update repo workflow

---

content/install_maintain/installation/_index.md
content/install_maintain/installation/certificates.md
content/install_maintain/installation/cfy-cluster-manager.md
content/install_maintain/installation/installation-modes.md
content/install_maintain/installation/installing-cli.md
content/install_maintain/installation/installing-cluster.md
content/install_maintain/installation/installing-external-db-and-queue-cluster.md
content/install_maintain/installation/installing-manager.md
content/install_maintain/installation/integrating-with-environments.md
content/install_maintain/installation/manager-image.md
content/install_maintain/installation/manager-license.md
content/install_maintain/installation/prerequisites.md
content/install_maintain/installation/three-nodes-cluster.md
content/ops_guides/backup_restore_guide.md

* Updating the structure and content of the installation section.
* Update content/install_maintain/installation/installation-modes.md
* Update content/install_maintain/installation/installation-modes.md
* Update content/install_maintain/installation/installing-external-db-and-queue-cluster.md

Updating the structure and content of the installation section. (#1523)

---

content/developer/writing_plugins/packaging-your-plugin.md

small fixes
add $ before commands
review fixes
small typo
one more fix

added wagon builders docs

---

content/install_maintain/installation/installing-cluster.md
content/install_maintain/installation/installing-external-db-and-queue-cluster.md
content/install_maintain/installation/prerequisites.md

Rewritten up to the `Cloudify Management Service` section.

CY-2859 Update things related to the new status-reporter

---

content/working_with/official_plugins/Infrastructure/aws.md

 added aws pipeline node documentation

---

content/cli/orch_cli/deployments.md

Adding the deployments' labels documentation.

RD-486 Labels documentation

---

jenkins/Jenkinsfile

RD-908 remove label (#1646)

---

content/trial_getting_started/examples/automation_tools/_index.md
content/trial_getting_started/examples/automation_tools/aws_ansible_basics.md
content/trial_getting_started/examples/automation_tools/azure_arm_basics.md

updated note
Updated title and weights

add note in ansible basics example and move it to level4

---

content/working_with/official_plugins/Orchestration/helm.md

add eks auth docs

---

content/cli/orch_cli/blueprints.md
content/cli/orch_cli/deployments.md

Updating the labels and filters documentation based on the recent changes.

RD-1978 Update labels and filters documentation

---

content/developer/blueprints/spec-blueprint-labels.md
content/developer/blueprints/spec-labels.md

Adding documentation about `labels` and `blueprint_labels` in blueprints.

RD-1468 Blueprint labels docs

---

content/working_with/official_plugins/Configuration/fabric.md

added the new input description

RD-1706-Fabric-plugin-non-recoverable-errors

---

content/working_with/official_plugins/Orchestration/terraform.md

fix typos
typos
fix terraform pull explanation

add terraform pull documentation

---

content/developer/blueprints/spec-intrinsic-functions.md

Add documentation  for `get_environment_capability` intrinsic function

RD-2150 Add docs for get_environment_capability

---

content/cli/orch_cli/install.md

Related to https://github.com/cloudify-cosmo/cloudify-cli/pull/1293

RD-2165 cfy install into a deployment group

---

content/working_with/official_plugins/Infrastructure/azure.md

delete space
fix numbering issue
fix numbering

add runtime props documentation

---

content/install_maintain/installation/cfy-cluster-manager.md

Bump cfy-cluster-manager to the latest version.

Bump cfy-cluster-manager to v1.0.9

---

content/bestpractices/agiledevelopment.md

Co-authored-by: ofercloudify <47001062+ofercloudify@users.noreply.github.com>

CYBL-1149 Remove modifying blueprints section (#1831)

---

content/working_with/official_plugins/Orchestration/terraform.md

formmating fixes
formmating fixes
more formmating fixes

update tf docs

---

content/working_with/official_plugins/Infrastructure/azure.md

update azure vm docs

---

content/working_with/official_plugins/Orchestration/helm.md

add helm ssl ca docs

---

content/working_with/console/widgets/filter.md

A cherry-pick of https://github.com/cloudify-cosmo/docs.getcloudify.org/pull/1880 to `6.0.0-build` branch. Required to merge https://github.com/cloudify-cosmo/cloudify-stage/pull/1443 and close RD-1829

RD-1829 Describe incompatibility between Resource Filter and Deployments View widgets

---

content/developer/writing_widgets/widgets-components.md

Update the version of UI components after 2.4.7 was released:
https://github.com/cloudify-cosmo/cloudify-ui-components/releases/tag/v2.4.7

RD-2690 Update version of UI components to 2.4.7

---

content/developer/writing_widgets/widget-apis.md

continuation of https://github.com/cloudify-cosmo/docs.getcloudify.org/pull/1907 changed branch name 
Remove jquery, $ api.

RD-2775 Update after jQuery removal

---

content/working_with/console/widgets/buttonLink.md

Updates "Button Link" widget documentation to be aligned with the changes from https://github.com/cloudify-cosmo/cloudify-stage/pull/1565/ .

RD-2936 Update "Button Link" widget documentation

---

content/developer/writing_widgets/widgets-components.md

As per https://github.com/cloudify-cosmo/cloudify-stage/pull/1597#issuecomment-918032175

RD-3100 Reverted components version update

---

content/install_maintain/installation/helm-chart/installing-helm-worker.md

RD-3305 add helm upgrade documentation

RD-3305 add helm upgrade documentation

---

content/install_maintain/installation/helm-chart/installing-helm-worker.md

RD-3305 helm upgrade

---

content/install_maintain/installation/helm-chart/installing-helm-worker.md

RD-3305 add helm upgrade documentation (#2014)

RD-3305 add helm upgrade documentation (#2014)

---

content/working_with/official_plugins/Infrastructure/aws.md

updated cloudify.nodes.aws.ec2.Image to include new Operations, and added a new example (#2030)
thank you

updated cloudify.nodes.aws.ec2.Image to include new Operations, and added a new example

---

content/developer/writing_widgets/widgets-components.md

Required to merge https://github.com/cloudify-cosmo/cloudify-stage/pull/1689

RD-3197 Updated cloudify-ui-components version

---

config.toml
content/working_with/console/customization/overrides.md
content/working_with/console/customization/user-configuration.md

Cherry-pick of #2115 onto `6.3.0-build` branch.

RD-4317 Improve documentation pages about product customization [6.3]

---

content/developer/blueprints/spec-inputs.md
content/developer/blueprints/spec-workflows.md

Three new data types with their specific constraints and display hints are described:
* textarea,
* blueprint_id,
* deployment_id.

RD-4107 Three new datatypes

---

content/developer/blueprints/spec-inputs.md

* node_instance
* scaling_group

RD-4696 New DSL data types documentation

---

content/working_with/console/widgets/blueprints.md

Documentation is being updated due to the [changes on stage repository](https://github.com/cloudify-cosmo/cloudify-stage/pull/1907)
Synchronization will be performed as a part of the [linked PR](https://github.com/cloudify-cosmo/cloudify-stage/pull/1907)

RD-3917: Updated Terraform Modal documentation

---

content/working_with/console/widgets/deployments.md

Documentation is being updated due to the changes introduced by [this PR](https://github.com/cloudify-cosmo/cloudify-stage/pull/1937)
Synchronization should take place as a part of the [linked PR](https://github.com/cloudify-cosmo/cloudify-stage/pull/1941)

RD-4651: Updated showFirstUserJourneyButtons parameter description

---

content/cli/orch_cli/workflows.md

- there's now also an `--all`
- the created_at column is gone, but availability_rules now exists

RD-4618 cfy workflows list: note on availability

---

content/cli/orch_cli/nodes.md

The extended view part is true right now. Will it always be true?
Who knows.

RD-4990 Add a note about `cfy nodes list --run-checks`

---

content/working_with/console/widgets/userGroups.md

Connected PR: https://github.com/cloudify-cosmo/cloudify-stage/pull/1998
Ticket: https://cloudifysource.atlassian.net/browse/RD-4339
There is a new dropdown in the User Group creation modal so I updated the docs about this widget.

RD-4339: Add tenants assignment to user group creation modal

---

content/install_maintain/installation/helm-chart/_index.md
content/install_maintain/installation/helm-chart/installing-helm-aio.md
content/install_maintain/installation/helm-chart/installing-helm-aks.md
content/install_maintain/installation/helm-chart/installing-helm-eks.md
content/install_maintain/installation/helm-chart/installing-helm-gke.md
content/install_maintain/installation/helm-chart/installing-helm-worker.md
content/trial_getting_started/set_trial_manager/install_with_helm.md

RD-5145 - [#2251](https://github.com/cloudify-cosmo/docs.getcloudify.org/pull/2251) backport to 6.3.0-build

RD-5145 update helm docs 6.3.0 backport

---

config.toml

[6.4] RD-4999 Update version parameter

---

content/install_maintain/installation/prerequisites.md

RD-4998-provide-details-about-supported-browsers-and-screen-sizes-in-user-documentation

---

content/install_maintain/installation/prerequisites.md

RD-4998-provide-details-about-supported-browsers-and-screen-sizes-in-user-documentation-640-build

---

content/bestpractices/agiledevelopmentbp.md

You can no longer read on the best practices for handling continuous
updates :)

Remove nonexistent reference

---

content/developer/blueprints/spec-inputs.md
content/developer/blueprints/spec-workflows.md

* More examples for the new inputs
* Fix the layout
* Add more workflow parameters' examples
this is a cherry-pick of https://github.com/cloudify-cosmo/docs.getcloudify.org/pull/2283

New types - more examples

---

content/install_maintain/installation/installing-cli.md

This is latest-build-based copy of https://github.com/cloudify-cosmo/docs.getcloudify.org/pull/2301

RD-5623 "Single file binary" CLI installation

---

content/working_with/workflows/built-in-workflows.md

No need to make the instance feel like a person.

Heal doc: replace `who` with `which`

---

content/developer/composer/blueprint-creation.md
content/developer/composer/features.md
content/developer/composer/getting-started.md
content/developer/composer/managing-inputs-outputs.md
content/developer/composer/managing-resources.md

Bases on changes from https://github.com/cloudify-cosmo/docs.getcloudify.org/pull/2265 which were removed (probably not intentionally) by https://github.com/cloudify-cosmo/docs.getcloudify.org/pull/2288.

CD-8 Updates after "Composer" section review

---

content/trial_getting_started/set_trial_manager/download_community.md
content/trial_getting_started/set_trial_manager/getting-started-with-cloudify-docker-and-cli.md
content/trial_getting_started/set_trial_manager/hosted_trial.md
content/trial_getting_started/set_trial_manager/install_with_helm.md
content/trial_getting_started/set_trial_manager/other-deployments.md
content/trial_getting_started/set_trial_manager/trial_install.md

* Changing the cloudify setup order and page naming
* fixing the page order and community start command
* Fixing docker community & premium commands, updating getting started CLI page
* align getting started community, cli, saas and premium
* fixing hosted_trial page
Co-authored-by: Alexander Molev <alex@Alexanders-MBP.lan>

Alex cm setup (#2343)

---

content/developer/writing_widgets/widgets-components.md

Updating `cloudify-ui-components` version after a recent [release of that package](https://github.com/cloudify-cosmo/cloudify-ui-components/releases/tag/v2.20.0)

RD-5715: Updated cloudify-ui-components version

---

content/cli/maint_cli/certificates.md
content/cli/maint_cli/clusters.md
content/cli/maint_cli/config.md
content/cli/maint_cli/init.md
content/cli/maint_cli/ldap.md
content/cli/maint_cli/license.md
content/cli/maint_cli/profiles.md
content/cli/maint_cli/sites.md
content/cli/maint_cli/snapshots.md
content/cli/maint_cli/ssh.md
content/cli/maint_cli/tenants.md
content/cli/maint_cli/use.md
content/cli/maint_cli/usergroups.md
content/cli/maint_cli/users.md
content/developer/apis/rest-client-python.md
content/developer/blueprints/spec-blueprint-labels.md
content/developer/blueprints/spec-capabilities.md
content/developer/blueprints/spec-imports.md
content/developer/blueprints/spec-inputs.md
content/developer/blueprints/spec-labels.md
content/developer/blueprints/spec-node-templates.md
content/developer/blueprints/spec-node-types.md
content/developer/blueprints/spec-outputs.md
content/developer/blueprints/spec-versioning.md
content/developer/blueprints/spec-workflows.md
content/developer/writing_plugins/plugins-common.html
content/working_with/manager/share-blueprint.md

Fxing dsl version references.

---

content/cli/orch_cli/deployments.md
content/working_with/manager/update-deployment.md
content/working_with/workflows/built-in-workflows.md

Description of the new dep-update workflow. Also some notes about the `update` and `check_drift` operations

RD-5992 New deployment-update docs

---

content/working_with/workflows/parameters.md

https://docs.cloudify.co/staging/RD-6091-intrinsic-fn-in-workflow-params-1/working_with/workflows/parameters/

RD-6091 Describe intrinsic functions in worflow parameters

---

content/trial_getting_started/introduction_to_blueprints/_index.md
content/trial_getting_started/introduction_to_blueprints/writing_blueprint.md

* Remove stale TODO
* Misc. grammatical and sentence changes
* Rewrite intro to BP writing
* Misc. typo fixes
* Update content/trial_getting_started/introduction_to_blueprints/writing_blueprint.md
Co-authored-by: Ahmad Musa <53178237+ahmadiesa-abu@users.noreply.github.com>
Co-authored-by: Ahmad Musa <53178237+ahmadiesa-abu@users.noreply.github.com>

Initial work on Getting Started guide (#2389)

---

content/developer/blueprints/spec-intrinsic-functions.md

Expand the note about node_instance_id a bit, and also mention node_instance_index as well.

RD-6445 get_attribute: note about node_instance_{id,index}

---

content/working_with/official_plugins/Orchestration/terraform.md

terraform plugin documentation update 6.2

terraform-import

---

content/working_with/workflows/built-in-workflows.md

No need to make the instance feel like a person.

Heal doc: replace `who` with `which` (#2320)

---

content/working_with/official_plugins/Orchestration/terraform.md

* CD-6 Update terraform features and reorganize
* CD-6 Add infracost config, operation and workflow

CD-6 Terraform enhancements infracost (#2321)

---

content/working_with/official_plugins/Orchestration/terraform.md

* CD-6 Update terraform features and reorganize
* CD-6 Add infracost config, operation and workflow
Co-authored-by: Anna <anna.szpoton@gmail.com>

CD-6 Terraform enhancements infracost (#2321) (#2420)

---

content/developer/writing_plugins/_index.md
content/developer/writing_plugins/creating-your-own-plugin.md

CD-4-Small-Changes (#2325)

---

content/cloudify_manager/premium/fully_distributed/logstash_elastic_logs.md

Adding the HOW TO documentation for the cloudify logs push to Elastic database

RD-5746 (#2322)

---

content/working_with/official_plugins/Configuration/ansible.md

* Add roles and change node operation
* Add paths management, workflow and relationship
* Remove relationship

Ansible (#2316)

---

content/working_with/official_plugins/Orchestration/terraform.md

terraform-import (#2405)

---

content/working_with/official_plugins/Orchestration/helm.md

* first version
* v2
* v3
* add check drift
* add check drift
* add check drift
Co-authored-by: nelynehemia <nely@cloudify.co>

RD-6055-helm-check-drift (#2459)

---

content/trial_getting_started/set_trial_manager/download_community.md

* fixing getting started community spelling
* fixing getting started community spelling, second part

fixing getting started community spelling (#2473)

---

content/cli/orch_cli/deployments.md
content/cli/orch_cli/executions.md

Add:
- deployment-groups
- deployment status-list
- execution-groups

RD-5208 CLI docs: add dep-groups, exec-groups

---

content/cli/orch_cli/deployments.md
content/cli/orch_cli/executions.md

* CLI docs: add `cfy dep status-list`
* CLI docs: add `cfy dep groups`
* CLI docs: also add execution-groups

RD-5208 CLI docs: add dep-groups, exec-groups (#2481)

---

config.toml
content/developer/writing_widgets/widgets-components.md

Versions update for 7.0 release.

RND-360 Update versions for UI packages [7.0]
